ls:
  /{components,layouts,middleware,pages,plugins,server,store,types}/*:
    .js: camelCase
    .ts: camelCase
    .vue: camelCase | PascalCase
    .d.ts: camelCase
    .spec.ts: camelCase | PascalCase
    .mock.ts: camelCase
