codecov:
  bot: money-heist-hunter
  token: ${{ secrets.CODECOV_TOKEN }}
  require_ci_to_pass: yes
coverage:
  round: up
  precision: 2
  range: '70...100'
parsers:
  javascript:
    enable_partials: yes
notify:
  after_n_builds: 5
  wait_for_ci: yes
  lark-suite:
    frontui:
      url: ${{ secrets.LARK_HOOK }}
      flags:
        - frontend
        - ui
      threshold: 1%
      only_pulls: false
      branches:
        - 'master'
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: true
  after_n_builds: 5
