# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      #The yarn cache directory will depend on your operating system and version of yarn
      #run cmd yarn cach dir to print out path 
    - name: Get yarn cache diretory path
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"
      
    - name: Cache dependencies
      id: yarn-cache
      # link https://github.com/actions/cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
           ${{ runner.os }}-yarn-

    - name: Install packages frozen
      run: yarn install -frozen-lockfile
    - name: Run Test case
      run: yarn test
